version: "3.8"

services:
    nginx_app:
        build:
            context: .
            dockerfile: nginx_app.Dockerfile
        ports:
            - 8002:80
        volumes:
            - ./api:/api
    uvicorn:
        build:
            context: .
            dockerfile: uvicorn.Dockerfile
        ports:
            - 8001:8000
        volumes:
            - ./api:/api
    nginx_proxy:
        build:
            context: .
            dockerfile: nginx_proxy.Dockerfile
        ports:
            - 8003:80
        volumes:
            - ./nginx_proxy/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - uvicorn